const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const crypto=require('node:crypto');
function env(){
 let now='2026-09-30T17:59:00Z';class Clock extends Date{constructor(...a){super(...(a.length?a:[now]));}};
 const fmt=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Omsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
 class Sheet{constructor(id,rows){this.id=id;this.rows=rows;}getLastRow(){return this.rows.length}getMaxRows(){return 1000}getRange(row,col,n=1,m=1){const self=this;return {getValues(){return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.rows[row+i-1]?.[col+j-1]??''))},setValues(values){values.forEach((r,i)=>r.forEach((v,j)=>{self.rows[row+i-1]??=[];self.rows[row+i-1][col+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v}));return this},setValue(v){return this.setValues([[v]])},setNumberFormat(){return this},setVerticalAlignment(){return this},setWrap(){return this}}}getDataRange(){return this.getRange(1,1,this.rows.length,4)}}
 const registry=new Sheet(0,[['ID','Имя','Цель','ID листа'],['p1','Человек один','',1],['p2','Человек два','',2],['p3','Человек три','',3]]);
 const sheets=[registry,...[1,2,3].map(i=>new Sheet(i,[['date','goal','today','tomorrow','insight','timestamp','revision','requestId']]))];
 const book={getSheetByName:()=>registry,getSheetById:id=>sheets[id]};let locked=false;
 const context=vm.createContext({Date:Clock,console,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'book'})},SpreadsheetApp:{openById:()=>book,flush(){}},Utilities:{formatDate:fmt,parseDate:d=>new Clock(d+'T00:00:00+06:00'),getUuid:()=>crypto.randomUUID()},LockService:{getScriptLock:()=>({waitLock(){assert.equal(locked,false);locked=true},releaseLock(){locked=false}})}});
 vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../Code.gs'),'utf8'),context);
 const goal=(id='p1',g='Цель',expected='')=>context.saveGoal({participantId:id,goal:g,expectedGoal:expected});
 const payload=(extra={})=>({participantId:'p1',date:fmt(new Clock()),goal:'Цель',today:'Сегодня',tomorrow:'Завтра',insight:'Инсайт',requestId:crypto.randomUUID(),expectedRevision:null,...extra});
 return {context,sheets,goal,payload,setTime:x=>{now=x}};
}
test('required fields and unknown participant are rejected',()=>{const e=env();e.goal();for(const f of ['goal','today','tomorrow','insight'])assert.throws(()=>e.context.submitReport(e.payload({[f]:'  '})));assert.throws(()=>e.context.getParticipant({participantId:'wrong'}));assert.equal(e.sheets[1].rows.length,1)});
test('one row per day; retry idempotent; explicit update',()=>{const e=env();e.goal();const p=e.payload();const a=e.context.submitReport(p);const b=e.context.submitReport(p);assert.equal(a.report.revision,b.report.revision);assert.equal(e.sheets[1].rows.length,2);const c=e.context.submitReport(e.payload({expectedRevision:a.report.revision,today:'Исправлено'}));assert.equal(c.report.today,'Исправлено');assert.equal(e.sheets[1].rows.length,2)});
test('concurrent stale revision cannot overwrite report',()=>{const e=env();e.goal();e.context.submitReport(e.payload());assert.equal(e.context.submitReport(e.payload({today:'Stale'})).code,'CONFLICT');assert.equal(e.sheets[1].rows[1][2],'Сегодня')});
test('Omsk midnight creates new row and preserves historical goal',()=>{const e=env();e.goal();const p=e.payload();e.context.submitReport(p);e.setTime('2026-09-30T18:01:00Z');assert.equal(e.context.submitReport(p).code,'DATE_CHANGED');e.goal('p1','Новая цель','Цель');e.context.submitReport(e.payload({goal:'Новая цель'}));assert.equal(e.sheets[1].rows.length,3);assert.equal(e.sheets[1].rows[1][1],'Цель');assert.equal(e.sheets[1].rows[2][1],'Новая цель');assert.equal(e.context.getParticipant({participantId:'p1'}).report.date,'2026-10-01')});
test('participants and goals isolated; goal conflict detected',()=>{const e=env();e.goal();e.goal('p2','Другая цель');e.context.submitReport(e.payload());assert.equal(e.context.getParticipant({participantId:'p2'}).goal,'Другая цель');assert.equal(e.context.getParticipant({participantId:'p2'}).report,null);assert.equal(e.goal('p1','Stale','').conflict,true);assert.equal(e.context.submitReport(e.payload({goal:'Stale'})).code,'CONFLICT')});
test('formula-looking input is stored as literal text',()=>{const e=env();e.goal('p1','=SUM(A1:A2)');const r=e.context.submitReport(e.payload({goal:'=SUM(A1:A2)',today:'=IMPORTXML("url")'}));assert.equal(r.report.today,'=IMPORTXML("url")');assert.equal(e.context.literal_('=1+1'),"'=1+1");assert.equal(e.context.getParticipant({participantId:'p1'}).goal,'=SUM(A1:A2)')});
